#!/usr/bin/env bash
set -euo pipefail

NIXLOOM_LIBEXEC="${NIXLOOM_LIBEXEC:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PROJECT_DIR="${NIXLOOM_ROOT:-${NIXLOOM_LIBEXEC}}"
# shellcheck source=config/lib.sh
source "${NIXLOOM_LIBEXEC}/config/lib.sh"

CONFIG_ARG=""
DRY_RUN=0

usage() {
  printf '%s\n' 'Usage: ./scripts/hermes.sh [--config FILE] [--dry-run] [--help]'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      require_opt_value "$1" $#
      CONFIG_ARG="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

resolve_config_file "${PROJECT_DIR}" "${CONFIG_ARG}"
use_project_caches "${PROJECT_DIR}"

HERMES_HOST="127.0.0.1"
HERMES_PORT="$(cfg_required '.ports.hermes' 'ports.hermes')"
LLAMA_PORT="$(cfg_required '.ports.llama' 'ports.llama')"
LLAMA_URL="http://127.0.0.1:${LLAMA_PORT}/v1"
HERMES_HOME="${HERMES_HOME:-${PROJECT_DIR}/.hermes}"
SELF_IMPROVEMENT="$(cfg_bool_required '.hermes.self_improvement' 'hermes.self_improvement')"
SANDBOX="$(cfg_bool_required '.hermes.sandbox' 'hermes.sandbox')"
COMPRESSION_THRESHOLD="$(cfg_required '.hermes.compression.threshold' 'hermes.compression.threshold')"
COMPRESSION_ABORT_ON_FAILURE="$(cfg_bool_required '.hermes.compression.abort_on_summary_failure' 'hermes.compression.abort_on_summary_failure')"

HERMES_MODEL="$(llm_id)"
check_hermes_ctx
CTX_SIZE="$(llm_context)"

if ! is_number "${COMPRESSION_THRESHOLD}" \
  || ! awk -v value="${COMPRESSION_THRESHOLD}" 'BEGIN { exit !(value > 0 && value < 1) }'; then
  printf 'hermes.compression.threshold must be greater than 0 and less than 1.\n' >&2
  exit 2
fi

# The per-service key is generated by this launcher. Capture it in a non-exported
# variable before scrubbing .env names below.
HERMES_GATEWAY_RUNTIME_KEY_VALUE="${HERMES_API_KEY:-}"
if [[ -z "${HERMES_GATEWAY_RUNTIME_KEY_VALUE}" ]]; then
  HERMES_GATEWAY_RUNTIME_KEY_VALUE="$(generate_api_key)"
fi

if [[ "${SANDBOX}" == "1" && "${HERMES_HOME}" != "${PROJECT_DIR}"/* ]]; then
  printf 'hermes.sandbox only maps %s, so HERMES_HOME must live inside it (got %s).\n' \
    "${PROJECT_DIR}" "${HERMES_HOME}" >&2
  printf 'Move it under the project or set hermes.sandbox: false.\n' >&2
  exit 2
fi

# Drop any names defined by .env before starting the gateway, so secrets loaded
# by a service environment are not exposed to Hermes terminal tools. bwrap cannot pass
# an environment value off the command line, so --clearenv is deliberately not
# used: it would force API_SERVER_KEY into argv, where /proc exposes it.
if [[ -f "${PROJECT_DIR}/.env" ]]; then
  while IFS= read -r env_key; do
    [[ -n "${env_key}" ]] || continue
    unset "${env_key}" || true
  done < <(sed -nE 's/^[[:space:]]*(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=.*/\2/p' \
    "${PROJECT_DIR}/.env")
fi

model_json="$(jq -Rn --arg value "${HERMES_MODEL}" '$value')"
url_json="$(jq -Rn --arg value "${LLAMA_URL}" '$value')"
cwd_json="$(jq -Rn --arg value "${PROJECT_DIR}" '$value')"

# Use explicit API-server toolsets so browser automation is not registered.
# Web search remains enabled independently through the `web` toolset.
toolsets='    - web
    - terminal
    - file
    - skills
    - todo
    - memory
    - session_search'
self_improvement=false
if [[ "${SELF_IMPROVEMENT}" == "1" ]]; then
  self_improvement=true
fi
compression_abort=false
if [[ "${COMPRESSION_ABORT_ON_FAILURE}" == "1" ]]; then
  compression_abort=true
fi

config_content="model:
  provider: custom
  default: ${model_json}
  base_url: ${url_json}
  api_key: none
  context_length: ${CTX_SIZE}
compression:
  threshold: ${COMPRESSION_THRESHOLD}
  abort_on_summary_failure: ${compression_abort}
terminal:
  backend: local
  cwd: ${cwd_json}
memory:
  nudge_interval: $([[ "${self_improvement}" == true ]] && printf '10' || printf '0')
skills:
  creation_nudge_interval: $([[ "${self_improvement}" == true ]] && printf '10' || printf '0')
  disabled:
    - computer-use
curator:
  enabled: ${self_improvement}
platform_toolsets:
  api_server:
${toolsets}
"

# Confine the gateway (and therefore its terminal/file tools) to the state
# directory: system paths are read-only and /home is not mapped at all.
# Within the state directory, sensitive control files stay out of reach even
# though the rest is writable:
#   - a custom config inside the state directory is rebound read-only;
#     packaged config and executable launchers already live in the read-only
#     Nix store.
#   - .git is read-only when a legacy state directory is also a checkout.
#   - .env is masked entirely; the API tokens in it are not the agent's to read.
# The network namespace is shared rather than isolated because the gateway must
# reach llama-swap on loopback, and bwrap cannot share loopback alone.
launcher=()
if [[ "${SANDBOX}" == "1" ]]; then
  launcher=(
    bwrap
    --die-with-parent
    # Detach the controlling terminal so the sandbox cannot inject keystrokes
    # into the terminal that launched the stack.
    --new-session
    --unshare-all --share-net
    --proc /proc --dev /dev --tmpfs /tmp
    --ro-bind /nix /nix
    --ro-bind /etc /etc
    --ro-bind-try /bin /bin
    --ro-bind-try /usr /usr
    --ro-bind-try /run/nscd /run/nscd
    --ro-bind-try /run/current-system /run/current-system
    --bind "${PROJECT_DIR}" "${PROJECT_DIR}"
    # A legacy deployment may still place state in a source checkout.
    --ro-bind-try "${PROJECT_DIR}/.git" "${PROJECT_DIR}/.git"
    --setenv HOME "${HERMES_HOME}/home"
  )
  # Order matters: re-cover a mutable custom config inside the writable bind.
  if [[ "${NIXLOOM_CONFIG_FILE}" == "${PROJECT_DIR}"/* ]]; then
    launcher+=(--ro-bind "${NIXLOOM_CONFIG_FILE}" "${NIXLOOM_CONFIG_FILE}")
  fi
  if [[ -f "${PROJECT_DIR}/.env" ]]; then
    launcher+=(--ro-bind /dev/null "${PROJECT_DIR}/.env")
  fi
  launcher+=(--)
fi

if [[ "${DRY_RUN}" == "1" ]]; then
  printf 'HERMES_HOME=%q\n' "${HERMES_HOME}"
  printf 'HERMES_MODEL=%q\n' "${HERMES_MODEL}"
  printf 'HERMES_API_URL=http://%s:%s/v1\n' "${HERMES_HOST}" "${HERMES_PORT}"
  printf 'HERMES_SANDBOX=%q\n' "${SANDBOX}"
  printf '%s' "${config_content}"
  printf '%q ' "${launcher[@]}" hermes gateway
  printf '\n'
  exit 0
fi

if [[ "${SANDBOX}" == "1" ]] && ! command -v bwrap >/dev/null; then
  printf 'hermes.sandbox is enabled but bwrap is missing; re-enter the dev shell or set hermes.sandbox: false.\n' >&2
  exit 2
fi

mkdir -p "${HERMES_HOME}/home"
printf '%s' "${config_content}" >"${HERMES_HOME}/config.yaml"
chmod 600 "${HERMES_HOME}/config.yaml"

export HERMES_HOME
export API_SERVER_ENABLED=true
export API_SERVER_HOST="${HERMES_HOST}"
export API_SERVER_PORT="${HERMES_PORT}"
export API_SERVER_KEY="${HERMES_GATEWAY_RUNTIME_KEY_VALUE}"
export API_SERVER_MODEL_NAME=hermes-agent

exec "${launcher[@]}" hermes gateway
