#!/usr/bin/env bash
set -euo pipefail

NIXLOOM_LIBEXEC="${NIXLOOM_LIBEXEC:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
STATE_DIR="${NIXLOOM_STATE_DIR:-${XDG_STATE_HOME:-${HOME}/.local/state}/nixloom}"
DATA_DIR="${NIXLOOM_DATA_DIR:-${XDG_DATA_HOME:-${HOME}/.local/share}/nixloom}"
CACHE_DIR="${NIXLOOM_CACHE_DIR:-${XDG_CACHE_HOME:-${HOME}/.cache}/nixloom}"
# shellcheck source=config/lib.sh
source "${NIXLOOM_LIBEXEC}/config/lib.sh"

CONFIG_ARG=""
DRY_RUN=0

usage() {
  printf '%s\n' 'Usage: ./scripts/hermes.sh [--config FILE] [--dry-run] [--help]'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      require_opt_value "$1" $#
      CONFIG_ARG="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

resolve_config_file "${CONFIG_ARG}"
use_runtime_paths "${STATE_DIR}" "${DATA_DIR}" "${CACHE_DIR}"

HERMES_HOST="127.0.0.1"
HERMES_PORT="$(cfg_required '.ports.hermes' 'ports.hermes')"
LLAMA_PORT="$(cfg_required '.ports.llama' 'ports.llama')"
LLAMA_URL="http://127.0.0.1:${LLAMA_PORT}/v1"
HERMES_HOME="${HERMES_HOME:-${STATE_DIR}/.hermes}"
SELF_IMPROVEMENT="$(cfg_bool_required '.hermes.self_improvement' 'hermes.self_improvement')"
SANDBOX="$(cfg_bool_required '.hermes.sandbox' 'hermes.sandbox')"

if [[ "${SANDBOX}" == "1" ]]; then
  # Hermes only needs its gateway API and its own state; do not expose the
  # model data directory or its cache to terminal/file tools in the sandbox.
  export HF_HOME="${STATE_DIR}/.hf"
fi
COMPRESSION_THRESHOLD="$(cfg_required '.hermes.compression.threshold' 'hermes.compression.threshold')"
COMPRESSION_ABORT_ON_FAILURE="$(cfg_bool_required '.hermes.compression.abort_on_summary_failure' 'hermes.compression.abort_on_summary_failure')"

HERMES_MODEL="$(llm_id)"
check_hermes_ctx
CTX_SIZE="$(llm_context)"

if ! is_number "${COMPRESSION_THRESHOLD}" \
  || ! awk -v value="${COMPRESSION_THRESHOLD}" 'BEGIN { exit !(value > 0 && value < 1) }'; then
  printf 'hermes.compression.threshold must be greater than 0 and less than 1.\n' >&2
  exit 2
fi

# The per-service key is generated by this launcher.
HERMES_GATEWAY_RUNTIME_KEY_VALUE="${HERMES_API_KEY:-}"
if [[ -z "${HERMES_GATEWAY_RUNTIME_KEY_VALUE}" ]]; then
  HERMES_GATEWAY_RUNTIME_KEY_VALUE="$(generate_api_key)"
fi

if [[ "${SANDBOX}" == "1" && "${HERMES_HOME}" != "${STATE_DIR}"/* ]]; then
  printf 'hermes.sandbox only maps %s, so HERMES_HOME must live inside it (got %s).\n' \
    "${STATE_DIR}" "${HERMES_HOME}" >&2
  printf 'Move it under the state directory or set hermes.sandbox: false.\n' >&2
  exit 2
fi

model_json="$(jq -Rn --arg value "${HERMES_MODEL}" '$value')"
url_json="$(jq -Rn --arg value "${LLAMA_URL}" '$value')"
cwd_json="$(jq -Rn --arg value "${STATE_DIR}" '$value')"

# Use explicit API-server toolsets so browser automation is not registered.
# Web search remains enabled independently through the `web` toolset.
toolsets='    - web
    - terminal
    - file
    - skills
    - todo
    - memory
    - session_search'
self_improvement=false
if [[ "${SELF_IMPROVEMENT}" == "1" ]]; then
  self_improvement=true
fi
compression_abort=false
if [[ "${COMPRESSION_ABORT_ON_FAILURE}" == "1" ]]; then
  compression_abort=true
fi

config_content="model:
  provider: custom
  default: ${model_json}
  base_url: ${url_json}
  api_key: none
  context_length: ${CTX_SIZE}
compression:
  threshold: ${COMPRESSION_THRESHOLD}
  abort_on_summary_failure: ${compression_abort}
terminal:
  backend: local
  cwd: ${cwd_json}
memory:
  nudge_interval: $([[ "${self_improvement}" == true ]] && printf '10' || printf '0')
skills:
  creation_nudge_interval: $([[ "${self_improvement}" == true ]] && printf '10' || printf '0')
  disabled:
    - computer-use
curator:
  enabled: ${self_improvement}
platform_toolsets:
  api_server:
${toolsets}
"

# Confine the gateway (and therefore its terminal/file tools) to the state
# directory: system paths are read-only and /home is not mapped at all.
# The executable launchers and packaged config template live in the read-only
# Nix store, while the user config and credentials are masked from the agent.
# The network namespace is shared rather than isolated because the gateway must
# reach llama-swap on loopback, and bwrap cannot share loopback alone.
launcher=()
if [[ "${SANDBOX}" == "1" ]]; then
  launcher=(
    bwrap
    --die-with-parent
    # Detach the controlling terminal so the sandbox cannot inject keystrokes
    # into the terminal that launched the stack.
    --new-session
    --unshare-all --share-net
    --proc /proc --dev /dev --tmpfs /tmp
    --ro-bind /nix /nix
    --ro-bind /etc /etc
    --ro-bind-try /bin /bin
    --ro-bind-try /usr /usr
    --ro-bind-try /run/nscd /run/nscd
    --ro-bind-try /run/current-system /run/current-system
    --bind "${STATE_DIR}" "${STATE_DIR}"
    --setenv HOME "${HERMES_HOME}/home"
  )
  launcher+=(--setenv NIXLOOM_CONFIG_FILE /dev/null)
  launcher+=(--)
fi

if [[ "${DRY_RUN}" == "1" ]]; then
  printf 'HERMES_HOME=%q\n' "${HERMES_HOME}"
  printf 'HERMES_MODEL=%q\n' "${HERMES_MODEL}"
  printf 'HERMES_API_URL=http://%s:%s/v1\n' "${HERMES_HOST}" "${HERMES_PORT}"
  printf 'HERMES_SANDBOX=%q\n' "${SANDBOX}"
  printf '%s' "${config_content}"
  printf '%q ' "${launcher[@]}" hermes gateway
  printf '\n'
  exit 0
fi

if [[ "${SANDBOX}" == "1" ]] && ! command -v bwrap >/dev/null; then
  printf 'hermes.sandbox is enabled but bwrap is missing; re-enter the dev shell or set hermes.sandbox: false.\n' >&2
  exit 2
fi

mkdir -p "${HERMES_HOME}/home"
printf '%s' "${config_content}" >"${HERMES_HOME}/config.yaml"
chmod 600 "${HERMES_HOME}/config.yaml"

export HERMES_HOME
export API_SERVER_ENABLED=true
export API_SERVER_HOST="${HERMES_HOST}"
export API_SERVER_PORT="${HERMES_PORT}"
export API_SERVER_KEY="${HERMES_GATEWAY_RUNTIME_KEY_VALUE}"
export API_SERVER_MODEL_NAME=hermes-agent

exec "${launcher[@]}" hermes gateway
